package redhat.checklist;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Questionare implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Questionare() {
    }

}