package redhat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Question implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.lang.String question;
   private java.lang.String type;

   private java.lang.String date;

   private java.lang.String resultType;

   private java.lang.String answerType;

   private java.lang.String answer;

   private java.lang.String additionalAnswer;

   public Question()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getQuestion()
   {
      return this.question;
   }

   public void setQuestion(java.lang.String question)
   {
      this.question = question;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getDate()
   {
      return this.date;
   }

   public void setDate(java.lang.String date)
   {
      this.date = date;
   }

   public java.lang.String getResultType()
   {
      return this.resultType;
   }

   public void setResultType(java.lang.String resultType)
   {
      this.resultType = resultType;
   }

   public java.lang.String getAnswerType()
   {
      return this.answerType;
   }

   public void setAnswerType(java.lang.String answerType)
   {
      this.answerType = answerType;
   }

   public java.lang.String getAnswer()
   {
      return this.answer;
   }

   public void setAnswer(java.lang.String answer)
   {
      this.answer = answer;
   }

   public java.lang.String getAdditionalAnswer()
   {
      return this.additionalAnswer;
   }

   public void setAdditionalAnswer(java.lang.String additionalAnswer)
   {
      this.additionalAnswer = additionalAnswer;
   }

   public Question(java.lang.String id, java.lang.String question,
         java.lang.String type, java.lang.String date,
         java.lang.String resultType, java.lang.String answerType,
         java.lang.String answer, java.lang.String additionalAnswer)
   {
      this.id = id;
      this.question = question;
      this.type = type;
      this.date = date;
      this.resultType = resultType;
      this.answerType = answerType;
      this.answer = answer;
      this.additionalAnswer = additionalAnswer;
   }

}