package redhat;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Question implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String id;
   private java.lang.String question;
   private java.lang.String type;

   public Question()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getQuestion()
   {
      return this.question;
   }

   public void setQuestion(java.lang.String question)
   {
      this.question = question;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public Question(java.lang.String id, java.lang.String question,
         java.lang.String type)
   {
      this.id = id;
      this.question = question;
      this.type = type;
   }

}