package redhat.checklist;
import redhat.checklist.QandAContext;
import org.drools.core.spi.KnowledgeHelper;
function void createQuestionare(KnowledgeHelper droorsContxt , String id, String question,String type) {

    QandAContext qaContext = new  QandAContext( );
    qaContext.addQuestion( "1", "Are the building contents being taken as collateral by the borrower or related entity? Either by UCC or stated within the mortgage.", "YorN" );
    //kcontext.insert(qaContext); 


}
