package redhat.checklist;
import redhat.checklist.QandAContext
function void createQuestionare(String id, String question,String type) {

    QandAContext qaContet = new  QandAContext( );
    qaContext.addQuestion( "1", "Are the building contents being taken as collateral by the borrower or related entity? Either by UCC or stated within the mortgage.", "YorN" );
    //kcontext.insert(qaContext); 


}
